import type { Playbook } from "./index";

// Node spacing constants
const NODE_WIDTH = 200;
const H_GAP = 80;
const V_GAP = 60;

export const patterns: Record<string, Playbook> = {
  // ========== DATA PATTERNS ==========
  "pattern.data-analyze": {
    id: "pattern.data-analyze",
    name: "Data + Analyze",
    description: "Input data and run deep analysis",
    type: "pattern",
    category: "pattern",
    icon: "Lightbulb",
    color: "#8b5cf6",
    tags: ["data", "analysis", "basic"],
    entryPoints: ["input"],
    exitPoints: ["analysis"],
    nodes: [
      {
        relativeId: "input",
        primitiveId: "data.input",
        offsetX: 0,
        offsetY: 0,
        label: "Data Input",
        config: { dataType: "json" },
      },
      {
        relativeId: "analysis",
        primitiveId: "reason.analyze",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: 0,
        label: "Deep Analysis",
        config: { prompt: "Analyze the provided data" },
      },
    ],
    edges: [
      { sourceRelativeId: "input", targetRelativeId: "analysis", targetHandle: "data" },
    ],
  },

  "pattern.fetch-parse": {
    id: "pattern.fetch-parse",
    name: "Fetch + Parse",
    description: "Fetch external data and parse documents",
    type: "pattern",
    category: "pattern",
    icon: "Globe",
    color: "#3b82f6",
    tags: ["api", "fetch", "parse"],
    entryPoints: ["fetch"],
    exitPoints: ["parse"],
    nodes: [
      {
        relativeId: "fetch",
        primitiveId: "data.api.fetch",
        offsetX: 0,
        offsetY: 0,
        label: "API Fetch",
        config: { method: "GET" },
      },
      {
        relativeId: "parse",
        primitiveId: "data.doc.parse",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: 0,
        label: "Document Parse",
        config: { extractTables: true },
      },
    ],
    edges: [
      { sourceRelativeId: "fetch", targetRelativeId: "parse", sourceHandle: "response", targetHandle: "file" },
    ],
  },

  // ========== SIMULATION PATTERNS ==========
  "pattern.monte-carlo-setup": {
    id: "pattern.monte-carlo-setup",
    name: "Monte Carlo Setup",
    description: "Standard Monte Carlo simulation with uncertainty aggregation",
    type: "pattern",
    category: "pattern",
    icon: "Users",
    color: "#f59e0b",
    tags: ["monte-carlo", "simulation", "uncertainty"],
    entryPoints: ["scenario"],
    exitPoints: ["uncertainty", "chart"],
    nodes: [
      {
        relativeId: "scenario",
        primitiveId: "sim.scenario",
        offsetX: 0,
        offsetY: 0,
        label: "Scenario Setup",
        config: { count: 3, includeWorstCase: true },
      },
      {
        relativeId: "monte-carlo",
        primitiveId: "sim.montecarlo.oasis",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: 0,
        label: "Monte Carlo Simulation",
        config: { populationSize: 1000, rollouts: 1000, domain: "enterprise" },
      },
      {
        relativeId: "uncertainty",
        primitiveId: "uncertainty.aggregate",
        offsetX: (NODE_WIDTH + H_GAP) * 2,
        offsetY: -V_GAP / 2,
        label: "Uncertainty Aggregation",
        config: { aggregationMethod: "monte-carlo-propagation", separateEpistemic: true },
      },
      {
        relativeId: "chart",
        primitiveId: "output.chart",
        offsetX: (NODE_WIDTH + H_GAP) * 2,
        offsetY: V_GAP / 2,
        label: "Distribution Chart",
        config: { chartType: "bar", interactive: true },
      },
    ],
    edges: [
      { sourceRelativeId: "scenario", targetRelativeId: "monte-carlo", sourceHandle: "scenarios", targetHandle: "scenario" },
      { sourceRelativeId: "monte-carlo", targetRelativeId: "uncertainty", sourceHandle: "outcomeDistribution", targetHandle: "distributions" },
      { sourceRelativeId: "monte-carlo", targetRelativeId: "chart", sourceHandle: "outcomeDistribution", targetHandle: "data" },
    ],
  },

  "pattern.sensitivity-tornado": {
    id: "pattern.sensitivity-tornado",
    name: "Sensitivity + Tornado",
    description: "Sensitivity analysis with tornado chart visualization",
    type: "pattern",
    category: "pattern",
    icon: "BarChart2",
    color: "#f59e0b",
    tags: ["sensitivity", "tornado", "visualization"],
    entryPoints: ["model"],
    exitPoints: ["chart"],
    nodes: [
      {
        relativeId: "model",
        primitiveId: "sim.sensitivity",
        offsetX: 0,
        offsetY: 0,
        label: "Sensitivity Analysis",
        config: { range: 20 },
      },
      {
        relativeId: "chart",
        primitiveId: "output.chart",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: 0,
        label: "Tornado Chart",
        config: { chartType: "tornado", interactive: true },
      },
    ],
    edges: [
      { sourceRelativeId: "model", targetRelativeId: "chart", sourceHandle: "drivers", targetHandle: "data" },
    ],
  },

  // ========== HUMAN-IN-LOOP PATTERNS ==========
  "pattern.human-gate": {
    id: "pattern.human-gate",
    name: "Human Approval Gate",
    description: "Add human approval checkpoint before proceeding",
    type: "pattern",
    category: "pattern",
    icon: "ShieldCheck",
    color: "#ec4899",
    tags: ["human", "approval", "gate", "checkpoint"],
    entryPoints: ["context"],
    exitPoints: ["approved"],
    nodes: [
      {
        relativeId: "context",
        primitiveId: "reason.summarize",
        offsetX: 0,
        offsetY: 0,
        label: "Context Summary",
        config: { length: "brief", style: "executive" },
      },
      {
        relativeId: "approval",
        primitiveId: "human.approve",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: 0,
        label: "Approval Gate",
        config: { timeout: 24 },
      },
      {
        relativeId: "approved",
        primitiveId: "control.condition",
        offsetX: (NODE_WIDTH + H_GAP) * 2,
        offsetY: 0,
        label: "Check Approval",
        config: { operator: "equals", compareValue: "true" },
      },
    ],
    edges: [
      { sourceRelativeId: "context", targetRelativeId: "approval", sourceHandle: "summary", targetHandle: "context" },
      { sourceRelativeId: "approval", targetRelativeId: "approved", sourceHandle: "approved", targetHandle: "value" },
    ],
  },

  "pattern.human-input-loop": {
    id: "pattern.human-input-loop",
    name: "Human Input Loop",
    description: "Collect human input and incorporate into analysis",
    type: "pattern",
    category: "pattern",
    icon: "User",
    color: "#ec4899",
    tags: ["human", "input", "feedback"],
    entryPoints: ["prompt-context"],
    exitPoints: ["merged-analysis"],
    nodes: [
      {
        relativeId: "prompt-context",
        primitiveId: "reason.summarize",
        offsetX: 0,
        offsetY: 0,
        label: "Generate Prompt",
        config: { length: "brief", style: "bullets" },
      },
      {
        relativeId: "human-input",
        primitiveId: "human.input",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: 0,
        label: "Get Human Input",
        config: { inputType: "text", timeout: 60 },
      },
      {
        relativeId: "merged-analysis",
        primitiveId: "control.merge",
        offsetX: (NODE_WIDTH + H_GAP) * 2,
        offsetY: 0,
        label: "Merge Input",
        config: { strategy: "object" },
      },
    ],
    edges: [
      { sourceRelativeId: "prompt-context", targetRelativeId: "human-input", sourceHandle: "summary" },
      { sourceRelativeId: "human-input", targetRelativeId: "merged-analysis", sourceHandle: "response", targetHandle: "input1" },
    ],
  },

  // ========== REASONING PATTERNS ==========
  "pattern.critique-steelman": {
    id: "pattern.critique-steelman",
    name: "Critique + Steelman",
    description: "Balanced analysis with devil's advocate and best case",
    type: "pattern",
    category: "pattern",
    icon: "Scale",
    color: "#8b5cf6",
    tags: ["critique", "steelman", "balanced", "analysis"],
    entryPoints: ["plan-input"],
    exitPoints: ["balanced-view"],
    nodes: [
      {
        relativeId: "plan-input",
        primitiveId: "control.merge",
        offsetX: 0,
        offsetY: 0,
        label: "Plan Input",
        config: { strategy: "object" },
      },
      {
        relativeId: "critique",
        primitiveId: "reason.critique",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: -V_GAP,
        label: "Pre-Mortem",
        config: { perspective: "skeptic" },
      },
      {
        relativeId: "steelman",
        primitiveId: "reason.steelman",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: V_GAP,
        label: "Steelman Case",
        config: {},
      },
      {
        relativeId: "balanced-view",
        primitiveId: "reason.compare",
        offsetX: (NODE_WIDTH + H_GAP) * 2,
        offsetY: 0,
        label: "Balanced Assessment",
        config: { criteria: "Risks vs opportunities, probability-weighted" },
      },
    ],
    edges: [
      { sourceRelativeId: "plan-input", targetRelativeId: "critique", sourceHandle: "merged", targetHandle: "plan" },
      { sourceRelativeId: "plan-input", targetRelativeId: "steelman", sourceHandle: "merged", targetHandle: "option" },
      { sourceRelativeId: "critique", targetRelativeId: "balanced-view", sourceHandle: "critique", targetHandle: "options" },
      { sourceRelativeId: "steelman", targetRelativeId: "balanced-view", sourceHandle: "case", targetHandle: "options" },
    ],
  },

  "pattern.question-decompose": {
    id: "pattern.question-decompose",
    name: "Question Decomposition",
    description: "Break complex question into sub-questions with causal analysis",
    type: "pattern",
    category: "pattern",
    icon: "Network",
    color: "#8b5cf6",
    tags: ["decomposition", "causal", "questions"],
    entryPoints: ["question"],
    exitPoints: ["causal-graph"],
    nodes: [
      {
        relativeId: "question",
        primitiveId: "decompose.question",
        offsetX: 0,
        offsetY: 0,
        label: "Decompose Question",
        config: { maxDepth: 2, questionTypes: "factual,causal,counterfactual" },
      },
      {
        relativeId: "analysis",
        primitiveId: "reason.analyze",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: 0,
        label: "Answer Sub-Questions",
        config: { prompt: "Answer each sub-question systematically" },
      },
      {
        relativeId: "causal-graph",
        primitiveId: "causal.explain",
        offsetX: (NODE_WIDTH + H_GAP) * 2,
        offsetY: 0,
        label: "Causal Analysis",
        config: { method: "llm-reasoning", includeTornadoChart: true },
      },
    ],
    edges: [
      { sourceRelativeId: "question", targetRelativeId: "analysis", sourceHandle: "subQuestions", targetHandle: "data" },
      { sourceRelativeId: "analysis", targetRelativeId: "causal-graph", sourceHandle: "analysis", targetHandle: "simulationResults" },
      { sourceRelativeId: "question", targetRelativeId: "causal-graph", sourceHandle: "dependencies", targetHandle: "variables" },
    ],
  },

  // ========== BRANCHING PATTERNS ==========
  "pattern.multi-scenario": {
    id: "pattern.multi-scenario",
    name: "Multi-Scenario Branch",
    description: "Explore multiple scenarios in parallel with comparison",
    type: "pattern",
    category: "pattern",
    icon: "GitBranch",
    color: "#10b981",
    tags: ["scenario", "branch", "parallel", "comparison"],
    entryPoints: ["base-case"],
    exitPoints: ["comparison"],
    nodes: [
      {
        relativeId: "base-case",
        primitiveId: "sim.scenario",
        offsetX: 0,
        offsetY: 0,
        label: "Generate Scenarios",
        config: { count: 3, includeWorstCase: true },
      },
      {
        relativeId: "counterfactual",
        primitiveId: "branch.counterfactual",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: 0,
        label: "Counterfactual Analysis",
        config: { parallelExecution: true },
      },
      {
        relativeId: "comparison",
        primitiveId: "reason.compare",
        offsetX: (NODE_WIDTH + H_GAP) * 2,
        offsetY: 0,
        label: "Scenario Comparison",
        config: { criteria: "Expected value, risk, feasibility" },
      },
    ],
    edges: [
      { sourceRelativeId: "base-case", targetRelativeId: "counterfactual", sourceHandle: "scenarios", targetHandle: "baseScenario" },
      { sourceRelativeId: "counterfactual", targetRelativeId: "comparison", sourceHandle: "branches", targetHandle: "options" },
    ],
  },

  "pattern.conditional-flow": {
    id: "pattern.conditional-flow",
    name: "Conditional Flow",
    description: "Branch execution based on condition with merge",
    type: "pattern",
    category: "pattern",
    icon: "GitFork",
    color: "#6b7280",
    tags: ["conditional", "branch", "flow", "control"],
    entryPoints: ["condition"],
    exitPoints: ["merged"],
    nodes: [
      {
        relativeId: "condition",
        primitiveId: "control.condition",
        offsetX: 0,
        offsetY: 0,
        label: "Check Condition",
        config: { operator: "greaterThan" },
      },
      {
        relativeId: "true-branch",
        primitiveId: "reason.analyze",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: -V_GAP,
        label: "True Branch",
        config: { prompt: "Process when condition is true" },
      },
      {
        relativeId: "false-branch",
        primitiveId: "reason.analyze",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: V_GAP,
        label: "False Branch",
        config: { prompt: "Process when condition is false" },
      },
      {
        relativeId: "merged",
        primitiveId: "control.merge",
        offsetX: (NODE_WIDTH + H_GAP) * 2,
        offsetY: 0,
        label: "Merge Results",
        config: { strategy: "object" },
      },
    ],
    edges: [
      { sourceRelativeId: "condition", targetRelativeId: "true-branch", sourceHandle: "true", targetHandle: "data" },
      { sourceRelativeId: "condition", targetRelativeId: "false-branch", sourceHandle: "false", targetHandle: "data" },
      { sourceRelativeId: "true-branch", targetRelativeId: "merged", sourceHandle: "analysis", targetHandle: "input1" },
      { sourceRelativeId: "false-branch", targetRelativeId: "merged", sourceHandle: "analysis", targetHandle: "input2" },
    ],
  },

  // ========== OUTPUT PATTERNS ==========
  "pattern.recommendation-report": {
    id: "pattern.recommendation-report",
    name: "Recommendation + Report",
    description: "Generate recommendation with full evidence pack",
    type: "pattern",
    category: "pattern",
    icon: "CheckCircle",
    color: "#22c55e",
    tags: ["recommendation", "report", "output"],
    entryPoints: ["analysis-input"],
    exitPoints: ["report"],
    nodes: [
      {
        relativeId: "analysis-input",
        primitiveId: "control.merge",
        offsetX: 0,
        offsetY: 0,
        label: "Collect Evidence",
        config: { strategy: "object" },
      },
      {
        relativeId: "recommendation",
        primitiveId: "output.recommendation",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: 0,
        label: "Recommendation",
        config: { style: "bluf", includeConfidence: true },
      },
      {
        relativeId: "report",
        primitiveId: "output.report",
        offsetX: (NODE_WIDTH + H_GAP) * 2,
        offsetY: 0,
        label: "Evidence Pack",
        config: { format: "executive" },
      },
    ],
    edges: [
      { sourceRelativeId: "analysis-input", targetRelativeId: "recommendation", sourceHandle: "merged", targetHandle: "analysis" },
      { sourceRelativeId: "recommendation", targetRelativeId: "report", sourceHandle: "recommendation", targetHandle: "recommendation" },
      { sourceRelativeId: "analysis-input", targetRelativeId: "report", sourceHandle: "merged", targetHandle: "evidence" },
    ],
  },
};
