import type { Playbook } from "./index";

// Node spacing constants
const NODE_WIDTH = 200;
const NODE_HEIGHT = 80;
const H_GAP = 80;
const V_GAP = 60;

export const templates: Record<string, Playbook> = {
  // ========== STRATEGY TEMPLATES ==========
  "template.market-expansion": {
    id: "template.market-expansion",
    name: "Market Expansion Analysis",
    description: "Evaluate new market entry with competitive dynamics and risk assessment",
    type: "template",
    category: "strategy",
    icon: "TrendingUp",
    color: "#8b5cf6",
    tags: ["market", "expansion", "strategy", "growth"],
    entryPoints: ["data-input"],
    exitPoints: ["recommendation"],
    nodes: [
      {
        relativeId: "data-input",
        primitiveId: "data.input",
        offsetX: 0,
        offsetY: 0,
        label: "Market Data",
        config: { dataType: "json" },
      },
      {
        relativeId: "market-analysis",
        primitiveId: "reason.analyze",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: -V_GAP,
        label: "Market Analysis",
        config: { prompt: "Analyze market size, growth rate, and key segments" },
      },
      {
        relativeId: "competitor-scan",
        primitiveId: "reason.analyze",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: V_GAP,
        label: "Competitor Scan",
        config: { prompt: "Identify key competitors, their strengths and market share" },
      },
      {
        relativeId: "scenario-model",
        primitiveId: "sim.scenario",
        offsetX: (NODE_WIDTH + H_GAP) * 2,
        offsetY: 0,
        label: "Entry Scenarios",
        config: { count: 3, includeWorstCase: true },
      },
      {
        relativeId: "game-theory",
        primitiveId: "game.equilibrium",
        offsetX: (NODE_WIDTH + H_GAP) * 3,
        offsetY: 0,
        label: "Competitive Response",
        config: { equilibriumType: "nash", useAgentNegotiation: true },
      },
      {
        relativeId: "recommendation",
        primitiveId: "output.recommendation",
        offsetX: (NODE_WIDTH + H_GAP) * 4,
        offsetY: 0,
        label: "Go/No-Go Decision",
        config: { style: "bluf", includeConfidence: true },
      },
    ],
    edges: [
      { sourceRelativeId: "data-input", targetRelativeId: "market-analysis", targetHandle: "data" },
      { sourceRelativeId: "data-input", targetRelativeId: "competitor-scan", targetHandle: "data" },
      { sourceRelativeId: "market-analysis", targetRelativeId: "scenario-model", sourceHandle: "analysis", targetHandle: "baseCase" },
      { sourceRelativeId: "competitor-scan", targetRelativeId: "game-theory", sourceHandle: "analysis", targetHandle: "players" },
      { sourceRelativeId: "scenario-model", targetRelativeId: "game-theory", sourceHandle: "scenarios", targetHandle: "payoffs" },
      { sourceRelativeId: "game-theory", targetRelativeId: "recommendation", sourceHandle: "equilibrium", targetHandle: "analysis" },
    ],
  },

  "template.competitive-response": {
    id: "template.competitive-response",
    name: "Competitive Response",
    description: "Model competitor reactions and optimal counter-strategies",
    type: "template",
    category: "strategy",
    icon: "Target",
    color: "#06b6d4",
    tags: ["competition", "strategy", "game-theory"],
    entryPoints: ["threat-input"],
    exitPoints: ["response-plan"],
    nodes: [
      {
        relativeId: "threat-input",
        primitiveId: "data.input",
        offsetX: 0,
        offsetY: 0,
        label: "Competitive Threat",
        config: { dataType: "json" },
      },
      {
        relativeId: "threat-analysis",
        primitiveId: "reason.analyze",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: 0,
        label: "Threat Assessment",
        config: { prompt: "Assess severity, timeline, and potential impact of competitive threat" },
      },
      {
        relativeId: "response-options",
        primitiveId: "reason.compare",
        offsetX: (NODE_WIDTH + H_GAP) * 2,
        offsetY: -V_GAP,
        label: "Response Options",
        config: { criteria: "Speed, cost, effectiveness, risk" },
      },
      {
        relativeId: "game-sim",
        primitiveId: "game.equilibrium",
        offsetX: (NODE_WIDTH + H_GAP) * 2,
        offsetY: V_GAP,
        label: "Game Simulation",
        config: { equilibriumType: "stackelberg", useAgentNegotiation: true },
      },
      {
        relativeId: "premortem",
        primitiveId: "reason.critique",
        offsetX: (NODE_WIDTH + H_GAP) * 3,
        offsetY: 0,
        label: "Pre-Mortem",
        config: { perspective: "competitor" },
      },
      {
        relativeId: "response-plan",
        primitiveId: "output.recommendation",
        offsetX: (NODE_WIDTH + H_GAP) * 4,
        offsetY: 0,
        label: "Response Strategy",
        config: { style: "detailed", includeConfidence: true },
      },
    ],
    edges: [
      { sourceRelativeId: "threat-input", targetRelativeId: "threat-analysis", targetHandle: "data" },
      { sourceRelativeId: "threat-analysis", targetRelativeId: "response-options", sourceHandle: "analysis", targetHandle: "options" },
      { sourceRelativeId: "threat-analysis", targetRelativeId: "game-sim", sourceHandle: "analysis", targetHandle: "players" },
      { sourceRelativeId: "response-options", targetRelativeId: "premortem", sourceHandle: "comparison", targetHandle: "plan" },
      { sourceRelativeId: "game-sim", targetRelativeId: "premortem", sourceHandle: "strategies", targetHandle: "plan" },
      { sourceRelativeId: "premortem", targetRelativeId: "response-plan", sourceHandle: "critique", targetHandle: "analysis" },
    ],
  },

  "template.ma-due-diligence": {
    id: "template.ma-due-diligence",
    name: "M&A Due Diligence",
    description: "Comprehensive acquisition target evaluation with synergy modeling",
    type: "template",
    category: "strategy",
    icon: "Scale",
    color: "#8b5cf6",
    tags: ["m&a", "acquisition", "due-diligence", "valuation"],
    entryPoints: ["target-data"],
    exitPoints: ["deal-recommendation"],
    nodes: [
      {
        relativeId: "target-data",
        primitiveId: "data.input",
        offsetX: 0,
        offsetY: 0,
        label: "Target Company Data",
        config: { dataType: "json" },
      },
      {
        relativeId: "financial-analysis",
        primitiveId: "reason.analyze",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: -V_GAP * 1.5,
        label: "Financial Analysis",
        config: { prompt: "Analyze revenue trends, margins, cash flow, and debt structure" },
      },
      {
        relativeId: "strategic-fit",
        primitiveId: "reason.analyze",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: 0,
        label: "Strategic Fit",
        config: { prompt: "Evaluate product/market fit, customer overlap, technology synergies" },
      },
      {
        relativeId: "risk-assessment",
        primitiveId: "reason.critique",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: V_GAP * 1.5,
        label: "Risk Assessment",
        config: { perspective: "skeptic" },
      },
      {
        relativeId: "synergy-model",
        primitiveId: "sim.montecarlo.oasis",
        offsetX: (NODE_WIDTH + H_GAP) * 2,
        offsetY: -V_GAP,
        label: "Synergy Simulation",
        config: { populationSize: 1000, rollouts: 500, domain: "enterprise" },
      },
      {
        relativeId: "valuation-scenarios",
        primitiveId: "sim.scenario",
        offsetX: (NODE_WIDTH + H_GAP) * 2,
        offsetY: V_GAP,
        label: "Valuation Scenarios",
        config: { count: 3, includeWorstCase: true },
      },
      {
        relativeId: "human-review",
        primitiveId: "human.approve",
        offsetX: (NODE_WIDTH + H_GAP) * 3,
        offsetY: 0,
        label: "Deal Committee Review",
        config: { approvers: "CFO, CEO, Board", requireAll: false },
      },
      {
        relativeId: "deal-recommendation",
        primitiveId: "output.report",
        offsetX: (NODE_WIDTH + H_GAP) * 4,
        offsetY: 0,
        label: "Deal Recommendation",
        config: { format: "executive" },
      },
    ],
    edges: [
      { sourceRelativeId: "target-data", targetRelativeId: "financial-analysis", targetHandle: "data" },
      { sourceRelativeId: "target-data", targetRelativeId: "strategic-fit", targetHandle: "data" },
      { sourceRelativeId: "target-data", targetRelativeId: "risk-assessment", targetHandle: "plan" },
      { sourceRelativeId: "financial-analysis", targetRelativeId: "synergy-model", sourceHandle: "analysis", targetHandle: "scenario" },
      { sourceRelativeId: "strategic-fit", targetRelativeId: "synergy-model", sourceHandle: "analysis", targetHandle: "distributions" },
      { sourceRelativeId: "risk-assessment", targetRelativeId: "valuation-scenarios", sourceHandle: "critique", targetHandle: "baseCase" },
      { sourceRelativeId: "synergy-model", targetRelativeId: "human-review", sourceHandle: "outcomeDistribution", targetHandle: "context" },
      { sourceRelativeId: "valuation-scenarios", targetRelativeId: "human-review", sourceHandle: "scenarios", targetHandle: "context" },
      { sourceRelativeId: "human-review", targetRelativeId: "deal-recommendation", sourceHandle: "approved", targetHandle: "recommendation" },
    ],
  },

  // ========== OPERATIONAL TEMPLATES ==========
  "template.resource-allocation": {
    id: "template.resource-allocation",
    name: "Resource Allocation",
    description: "Optimize resource distribution across projects with constraints",
    type: "template",
    category: "operational",
    icon: "Users",
    color: "#f59e0b",
    tags: ["resources", "optimization", "allocation", "planning"],
    entryPoints: ["resource-data"],
    exitPoints: ["allocation-plan"],
    nodes: [
      {
        relativeId: "resource-data",
        primitiveId: "data.input",
        offsetX: 0,
        offsetY: 0,
        label: "Resource Pool",
        config: { dataType: "json" },
      },
      {
        relativeId: "project-data",
        primitiveId: "data.input",
        offsetX: 0,
        offsetY: V_GAP * 1.5,
        label: "Project Requirements",
        config: { dataType: "json" },
      },
      {
        relativeId: "constraint-analysis",
        primitiveId: "reason.analyze",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: V_GAP * 0.75,
        label: "Constraint Analysis",
        config: { prompt: "Identify hard constraints, soft constraints, and trade-offs" },
      },
      {
        relativeId: "pareto-opt",
        primitiveId: "opt.pareto",
        offsetX: (NODE_WIDTH + H_GAP) * 2,
        offsetY: 0,
        label: "Multi-Objective Optimization",
        config: { iterations: 1000, populationSize: 100 },
      },
      {
        relativeId: "sensitivity",
        primitiveId: "sim.sensitivity",
        offsetX: (NODE_WIDTH + H_GAP) * 2,
        offsetY: V_GAP * 1.5,
        label: "Sensitivity Analysis",
        config: { range: 20 },
      },
      {
        relativeId: "allocation-plan",
        primitiveId: "output.recommendation",
        offsetX: (NODE_WIDTH + H_GAP) * 3,
        offsetY: V_GAP * 0.75,
        label: "Allocation Plan",
        config: { style: "detailed", includeConfidence: true },
      },
    ],
    edges: [
      { sourceRelativeId: "resource-data", targetRelativeId: "constraint-analysis", targetHandle: "data" },
      { sourceRelativeId: "project-data", targetRelativeId: "constraint-analysis", targetHandle: "context" },
      { sourceRelativeId: "constraint-analysis", targetRelativeId: "pareto-opt", sourceHandle: "analysis", targetHandle: "objectives" },
      { sourceRelativeId: "constraint-analysis", targetRelativeId: "pareto-opt", sourceHandle: "analysis", targetHandle: "constraints" },
      { sourceRelativeId: "pareto-opt", targetRelativeId: "sensitivity", sourceHandle: "frontier", targetHandle: "model" },
      { sourceRelativeId: "pareto-opt", targetRelativeId: "allocation-plan", sourceHandle: "tradeoffs", targetHandle: "analysis" },
      { sourceRelativeId: "sensitivity", targetRelativeId: "allocation-plan", sourceHandle: "drivers", targetHandle: "analysis" },
    ],
  },

  "template.risk-assessment": {
    id: "template.risk-assessment",
    name: "Risk Assessment",
    description: "Comprehensive risk identification, quantification, and mitigation planning",
    type: "template",
    category: "operational",
    icon: "Shield",
    color: "#ef4444",
    tags: ["risk", "assessment", "mitigation", "planning"],
    entryPoints: ["context-input"],
    exitPoints: ["risk-report"],
    nodes: [
      {
        relativeId: "context-input",
        primitiveId: "data.input",
        offsetX: 0,
        offsetY: 0,
        label: "Project/Initiative Context",
        config: { dataType: "json" },
      },
      {
        relativeId: "risk-identification",
        primitiveId: "reason.analyze",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: 0,
        label: "Risk Identification",
        config: { prompt: "Identify all potential risks across categories: operational, financial, strategic, compliance" },
      },
      {
        relativeId: "risk-quantification",
        primitiveId: "sim.montecarlo.oasis",
        offsetX: (NODE_WIDTH + H_GAP) * 2,
        offsetY: -V_GAP,
        label: "Risk Quantification",
        config: { populationSize: 500, rollouts: 1000, domain: "enterprise" },
      },
      {
        relativeId: "premortem",
        primitiveId: "reason.critique",
        offsetX: (NODE_WIDTH + H_GAP) * 2,
        offsetY: V_GAP,
        label: "Pre-Mortem Analysis",
        config: { perspective: "skeptic" },
      },
      {
        relativeId: "mitigation-options",
        primitiveId: "reason.compare",
        offsetX: (NODE_WIDTH + H_GAP) * 3,
        offsetY: 0,
        label: "Mitigation Options",
        config: { criteria: "Effectiveness, cost, implementation complexity" },
      },
      {
        relativeId: "risk-report",
        primitiveId: "output.report",
        offsetX: (NODE_WIDTH + H_GAP) * 4,
        offsetY: 0,
        label: "Risk Report",
        config: { format: "detailed" },
      },
    ],
    edges: [
      { sourceRelativeId: "context-input", targetRelativeId: "risk-identification", targetHandle: "data" },
      { sourceRelativeId: "risk-identification", targetRelativeId: "risk-quantification", sourceHandle: "analysis", targetHandle: "scenario" },
      { sourceRelativeId: "risk-identification", targetRelativeId: "premortem", sourceHandle: "analysis", targetHandle: "plan" },
      { sourceRelativeId: "risk-quantification", targetRelativeId: "mitigation-options", sourceHandle: "outcomeDistribution", targetHandle: "options" },
      { sourceRelativeId: "premortem", targetRelativeId: "mitigation-options", sourceHandle: "critique", targetHandle: "options" },
      { sourceRelativeId: "mitigation-options", targetRelativeId: "risk-report", sourceHandle: "comparison", targetHandle: "recommendation" },
    ],
  },

  // ========== FINANCIAL TEMPLATES ==========
  "template.investment-analysis": {
    id: "template.investment-analysis",
    name: "Investment Analysis",
    description: "Evaluate investment opportunities with uncertainty quantification",
    type: "template",
    category: "financial",
    icon: "TrendingUp",
    color: "#22c55e",
    tags: ["investment", "roi", "npv", "financial"],
    entryPoints: ["investment-data"],
    exitPoints: ["investment-decision"],
    nodes: [
      {
        relativeId: "investment-data",
        primitiveId: "data.input",
        offsetX: 0,
        offsetY: 0,
        label: "Investment Opportunity",
        config: { dataType: "json" },
      },
      {
        relativeId: "financial-model",
        primitiveId: "reason.analyze",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: 0,
        label: "Financial Model",
        config: { prompt: "Build NPV, IRR, payback period model with key assumptions" },
      },
      {
        relativeId: "monte-carlo",
        primitiveId: "sim.montecarlo.oasis",
        offsetX: (NODE_WIDTH + H_GAP) * 2,
        offsetY: -V_GAP,
        label: "Return Distribution",
        config: { populationSize: 1000, rollouts: 1000, domain: "enterprise" },
      },
      {
        relativeId: "sensitivity",
        primitiveId: "sim.sensitivity",
        offsetX: (NODE_WIDTH + H_GAP) * 2,
        offsetY: V_GAP,
        label: "Sensitivity Analysis",
        config: { range: 25 },
      },
      {
        relativeId: "uncertainty-agg",
        primitiveId: "uncertainty.aggregate",
        offsetX: (NODE_WIDTH + H_GAP) * 3,
        offsetY: 0,
        label: "Uncertainty Aggregation",
        config: { aggregationMethod: "monte-carlo-propagation", separateEpistemic: true },
      },
      {
        relativeId: "visualization",
        primitiveId: "output.chart",
        offsetX: (NODE_WIDTH + H_GAP) * 4,
        offsetY: -V_GAP,
        label: "Return Distribution Chart",
        config: { chartType: "tornado", interactive: true },
      },
      {
        relativeId: "investment-decision",
        primitiveId: "output.recommendation",
        offsetX: (NODE_WIDTH + H_GAP) * 4,
        offsetY: V_GAP,
        label: "Investment Decision",
        config: { style: "bluf", includeConfidence: true },
      },
    ],
    edges: [
      { sourceRelativeId: "investment-data", targetRelativeId: "financial-model", targetHandle: "data" },
      { sourceRelativeId: "financial-model", targetRelativeId: "monte-carlo", sourceHandle: "analysis", targetHandle: "scenario" },
      { sourceRelativeId: "financial-model", targetRelativeId: "sensitivity", sourceHandle: "analysis", targetHandle: "model" },
      { sourceRelativeId: "monte-carlo", targetRelativeId: "uncertainty-agg", sourceHandle: "outcomeDistribution", targetHandle: "distributions" },
      { sourceRelativeId: "sensitivity", targetRelativeId: "uncertainty-agg", sourceHandle: "drivers", targetHandle: "correlations" },
      { sourceRelativeId: "uncertainty-agg", targetRelativeId: "visualization", sourceHandle: "uncertaintyBreakdown", targetHandle: "data" },
      { sourceRelativeId: "uncertainty-agg", targetRelativeId: "investment-decision", sourceHandle: "aggregatedDistribution", targetHandle: "analysis" },
    ],
  },

  "template.pricing-analysis": {
    id: "template.pricing-analysis",
    name: "Pricing Analysis",
    description: "Analyze pricing decisions with demand elasticity and competitive dynamics",
    type: "template",
    category: "financial",
    icon: "DollarSign",
    color: "#22c55e",
    tags: ["pricing", "elasticity", "revenue", "optimization"],
    entryPoints: ["pricing-context"],
    exitPoints: ["pricing-recommendation"],
    nodes: [
      {
        relativeId: "pricing-context",
        primitiveId: "data.input",
        offsetX: 0,
        offsetY: 0,
        label: "Pricing Context",
        config: { dataType: "json" },
      },
      {
        relativeId: "elasticity-analysis",
        primitiveId: "reason.analyze",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: -V_GAP,
        label: "Demand Elasticity",
        config: { prompt: "Estimate price elasticity of demand by segment" },
      },
      {
        relativeId: "competitor-pricing",
        primitiveId: "reason.analyze",
        offsetX: NODE_WIDTH + H_GAP,
        offsetY: V_GAP,
        label: "Competitive Pricing",
        config: { prompt: "Analyze competitor pricing strategies and likely responses" },
      },
      {
        relativeId: "price-scenarios",
        primitiveId: "sim.scenario",
        offsetX: (NODE_WIDTH + H_GAP) * 2,
        offsetY: 0,
        label: "Price Scenarios",
        config: { count: 4, includeWorstCase: true },
      },
      {
        relativeId: "revenue-simulation",
        primitiveId: "sim.montecarlo.oasis",
        offsetX: (NODE_WIDTH + H_GAP) * 3,
        offsetY: 0,
        label: "Revenue Impact",
        config: { populationSize: 1000, rollouts: 500, domain: "enterprise" },
      },
      {
        relativeId: "pricing-recommendation",
        primitiveId: "output.recommendation",
        offsetX: (NODE_WIDTH + H_GAP) * 4,
        offsetY: 0,
        label: "Pricing Strategy",
        config: { style: "detailed", includeConfidence: true },
      },
    ],
    edges: [
      { sourceRelativeId: "pricing-context", targetRelativeId: "elasticity-analysis", targetHandle: "data" },
      { sourceRelativeId: "pricing-context", targetRelativeId: "competitor-pricing", targetHandle: "data" },
      { sourceRelativeId: "elasticity-analysis", targetRelativeId: "price-scenarios", sourceHandle: "analysis", targetHandle: "baseCase" },
      { sourceRelativeId: "competitor-pricing", targetRelativeId: "price-scenarios", sourceHandle: "analysis", targetHandle: "baseCase" },
      { sourceRelativeId: "price-scenarios", targetRelativeId: "revenue-simulation", sourceHandle: "scenarios", targetHandle: "scenario" },
      { sourceRelativeId: "elasticity-analysis", targetRelativeId: "revenue-simulation", sourceHandle: "analysis", targetHandle: "distributions" },
      { sourceRelativeId: "revenue-simulation", targetRelativeId: "pricing-recommendation", sourceHandle: "outcomeDistribution", targetHandle: "analysis" },
    ],
  },
};
